---
- name: ensure docker apt key is present
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: "{{ isset.docker.key.id }}"
    state: "{{ isset.docker.state }}"

- name: ensure docker apt repository is active
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    filename: docker
    state: "{{ isset.docker.state }}"

- apt:
    package: docker-ce
    update_cache: yes
    state: "{{ isset.docker.state }}"
