---
- name: ensure docker apt key
  apt_key:
    url: "{{ isset_docker_key_url }}"
    id: "{{ isset_docker_key_id }}"
    state: "{{ isset_docker_state }}"

- name: ensure docker apt repository
  apt_repository:
    repo: "{{ isset_docker_repo }}"
    filename: "{{ isset_docker_repo_filename }}"
    state: "{{ isset_docker_state }}"

- name: ensure docker
  apt:
    package: "{{ isset_docker_package }}"
    update_cache: yes
    state: "{{ isset_docker_state }}"
    purge: yes
    autoremove: yes

- name: make docker play nice with UFW
  lineinfile:
    path: /etc/default/docker
    line: 'DOCKER_OPTS="--iptables=false"'
    create: yes
  notify: restart docker
  when:
    - isset_docker_state == 'present'