---
- name: ensure docker apt key is present
  apt_key:
    url: "{{ isset_docker_key_url }}"
    id: "{{ isset_docker_key_id }}"
    state: "{{ isset_docker_state }}"

- name: ensure docker apt repository is active
  apt_repository:
    repo: "{{ isset_docker_repo }}"
    filename: "{{ isset_docker_repo_filename }}"
    state: "{{ isset_docker_state }}"

- name: ensure docker
  apt:
    package: "{{ isset_docker_package }}"
    update_cache: yes
    state: "{{ isset_docker_state }}"
    purge: yes
    autoremove: yes
